# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

VAGRANT_COMMAND = ARGV[0]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  # Original starting point of the base box, and deploy script
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "dsra-client"

  # Get all the software installed or the base box
  config.vm.provision :shell, :path => "install_software.sh"

  # Setup configuration for DSRA
  config.vm.provision "file", source: "./hadoop/hdfs-site.xml.template", destination: "/tmp/hdfs-site.xml.template"
  config.vm.provision "file", source: "./hadoop/core-site.xml.template", destination: "/tmp/core-site.xml.template"
  config.vm.provision :shell, :path => "configure.sh"

  config.vm.synced_folder "./spark", "/opt/spark/conf"

  #  iPython Notebook forwarded port
  #config.vm.network "forwarded_port", guest: 8888, host: 18888

  # To use the same network as the Host OS is
  #config.vm.network "public_network"

end
