#cloud-config


coreos:
  etcd2:
    proxy: on
    discovery-srv: dsra.local
    listen-client-urls: http://0.0.0.0:2379
  fleet:
    etcd_servers: http://10.105.0.1:2379,http://10.105.0.3:2379,http://10.105.0.5:2379,http://10.105.0.7:2379,http://10.105.0.9:2379
    metadata: role=worker

  #locksmith:
  #  endpoint: http://localhost:2379
  units:
  - name: etcd2.service
    command: start
  - name: fleet.service
    command: start
  #- name: flanneld.service
  #  drop-ins:
  #    - name: 50-network-config.conf
  #      content: |
  #        [Service]
  #        ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{"Network":"10.1.0.0/16"}'
  #  command: start
  - name: var-lib-docker.mount
    command: start
    content: |
       [Unit]
       Description=Mount ephemeral to /var/lib/docker
       Before=docker.service
       [Mount]
       What=/dev/sda
       Where=/var/lib/docker
       Type=btrfs
  - name: data.mount
    command: start
    content: |
       [Unit]
       Description=Mount data
       [Mount]
       What=/dev/sdb
       Where=/data
       Type=btrfs
  - name: systemd-networkd.service
    command: stop
  - name: down-interfaces.service
    command: start
    content: |
       [Service]
       Type=oneshot
       ExecStart=/usr/bin/ip link set eno1 down
       ExecStart=/usr/bin/ip addr flush dev eno1
       ExecStart=/usr/bin/ip link set eno2 down
       ExecStart=/usr/bin/ip addr flush dev eno2
  - name: 10-bond.netdev
    command: start
    content: |
      [NetDev]
      Name=bond0
      Kind=bond

      [Bond]
      Mode=6
  - name: 20-eno1.network
    command: start
    content: |
      [Match]
      Name=eno1

      [Network]
      Bond=bond0
  - name: 21-eno2.network
    command: start
    content: |
      [Match]
      Name=eno2

      [Network]
      Bond=bond0
  - name: 30-setup-bonded-dhcp.network
    command: start
    content: |
      [Match]
      Name=bond0

      [Network]
      DHCP=true
  - name: systemd-networkd.service
    command: start

write_files:
   - path: /etc/modprobe.d/bonding.conf
     permissions: 0644
     owner: root
     content: |
      options bonding mode=6 miimon=100
   - path: /etc/modules-load.d/bonding.conf
     permissions: 0644
     owner: root
     content: |
      bonding

ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFDeCKt/GYFLig9AViMGsCADyXpt3F/D62m2eJPmxUs4EQAT/R3KKMb34T5JIoTfD/AMMffFO4aiRey1YP9ezkbpCBgA6PSU3DO2E75Kb9Y4P+W0iJetGv0pfr8D1nI0bc1wCF96cvODrGwzpSu2tyHeh2IGNYZc3EiExvXb3GhhZ17sXTW5RfBYqgZiV1SJBCbCajeDP4c4ZAI2mW87nJGWXocvZltSKW/GJlNSzNxz6u4mKsKl8YgF812UGDZwbJdI46vFBQ/LKVd0A3nKhh7zMdZU/kYYc1xgUJGHgXr5LM8UK7EhLeHOwLazQPw2mL3EF6kQn6g8FGmQgdeFrb
