#cloud-config


coreos:
  etcd2:
    proxy: on
    discovery-srv: dsra.local
    listen-client-urls: http://0.0.0.0:2379
  fleet:
    etcd_servers: http://10.105.0.1:2379,http://10.105.0.3:2379,http://10.105.0.5:2379,http://10.105.0.7:2379,http://10.105.0.9:2379
    metadata: role=worker

  #locksmith:
  #  endpoint: http://localhost:2379
  units:
  - name: etcd2.service
    command: start
  - name: fleet.service
    command: start
  #- name: flanneld.service
  #  drop-ins:
  #    - name: 50-network-config.conf
  #      content: |
  #        [Service]
  #        ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{"Network":"10.1.0.0/16"}'
  #  command: start
  - name: var-lib-docker.mount
    command: start
    content: |
       [Unit]
       Description=Mount ephemeral to /var/lib/docker
       Before=docker.service
       [Mount]
       What=/dev/sda
       Where=/var/lib/docker
       Type=btrfs
  - name: data.mount
    command: start
    content: |
       [Unit]
       Description=Mount data
       [Mount]
       What=/dev/sdb
       Where=/data
       Type=btrfs
  - name: reset-interfaces.service
    command: start
    content: |
     [Unit]
      Description=Setting interfaces to down and restarting networking post boot.
      After=network-online.target

      [Service]
      Type=oneshot
      ExecStart=/tmp/reset-interfaces

write_files:
   - path: /tmp/reset-interfaces
     permissions: 0700
     owner: root
     content: |
      #!/bin/bash
      logger "Resetting network interfaces for bonding."
      ip link set eno1 down
      ip link set eno2 down
      systemctl restart systemd-networkd
      logger "Network interfaces have been reset"
      rm /tmp/reset-interfaces
   - path: /etc/systemd/network/10-eno1.network
     permissions: 0644
     owner: root
     content: |
      [Match]
      Name=eno1

      [Network]
      Bond=bond0
   - path: /etc/systemd/network/11-eno2.network
     permissions: 0644
     owner: root
     content: |
      [Match]
      Name=eno2

      [Network]
      Bond=bond0
   - path: /etc/systemd/network/20-bond.netdev
     permissions: 0644
     owner: root
     content: |
      [NetDev]
      Name=bond0
      Kind=bond

      [Bond]
      Mode=balance-alb
   - path: /etc/systemd/network/30-setup-bonded-dhcp.network
     permissions: 0644
     owner: root
     content: |
      [Match]
      Name=bond0

      [Network]
      DHCP=true
   - path: /etc/modules-load.d/bonding.conf
     permissions: 0644
     owner: root
     content: |
      alias bond0 bonding
      options bonding mode=6 primary=eno1 miimon=100

ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFDeCKt/GYFLig9AViMGsCADyXpt3F/D62m2eJPmxUs4EQAT/R3KKMb34T5JIoTfD/AMMffFO4aiRey1YP9ezkbpCBgA6PSU3DO2E75Kb9Y4P+W0iJetGv0pfr8D1nI0bc1wCF96cvODrGwzpSu2tyHeh2IGNYZc3EiExvXb3GhhZ17sXTW5RfBYqgZiV1SJBCbCajeDP4c4ZAI2mW87nJGWXocvZltSKW/GJlNSzNxz6u4mKsKl8YgF812UGDZwbJdI46vFBQ/LKVd0A3nKhh7zMdZU/kYYc1xgUJGHgXr5LM8UK7EhLeHOwLazQPw2mL3EF6kQn6g8FGmQgdeFrb
