version: 0.1
log:
  level: debug

storage:
  filesystem:
    rootdirectory: /data

http:
   addr: 10.105.255.249:5000
   net: tcp
   secret: askdravherqp305u235lkadjfalsdjkfsasdfasdf  
   tls:
      certificate: /certs/domain.crt
      key: /certs/domain.key
   debug:
     addr: 10.105.255.249:5001

auth:
   htpasswd:
      realm: basic-realm
      path: /auth/htpasswd
