
FROM hub.dsra.local:5000/cloudera/hue:3.9.0

MAINTAINER Matt Parker <matthew.parker@l3-com.com>

copy hue.ini /local/git/hue/desktop/conf/pseudo-distributed.ini

# CMD ["build/env/bin/hue","runserver","0.0.0.0:8000"]
