FROM logbase/hue:latest
MAINTAINER Matt Parker <matthew.parker@l3-com.com>

COPY hue.ini /local/git/hue/desktop/conf.dist/hue.ini
# COPY pseudo-distributed.ini > /local/git/hue/desktop/conf/pseudo-distributed.ini

EXPOSE 8020
EXPOSE 50070

